name: Build docker image and Push
on:
  release:
    types: [created]

jobs:
   build:
     runs-on: ubuntu-latest
     steps:
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: kimdictor/chintomi
          tags: ${{env.GIT_TAG}},latest
