name: Validate code

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: PHP Syntax Checker (Lint)
      uses: StephaneBour/actions-php-lint@7.3
      with:
        # Folder to check syntax
        dir: .
        
    - name: PHPUnit Test
      run: ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests/test-mdl-book
